### ISSUE TITLE
data of previous steps get lost on error in later steps

### ISSUE THREAD

**Issue by Metis77** [terminal42/contao-ajaxform#14]
If ajaxform is used together with mp-forms an error occurs on form errors.
This error does not occur, if mp-forms is used alone, without ajaxform.

how to reproduce:
1.) have some mandatory fields in step1, that may not be empty
2.) force error in step2, for example by leaving empty a mandatory field
3.) after fixing this error in step 2 and clicking next the form jumps back to step 1 with empty fields and showing errors where the mandatory fields of step1 became empty

what would I expect:
3.) after fixing the errors form step2 the form should jump to next step3.

I could reproduce this issue on Contao 4.4 and 4.7.
Feel free to test yourself:
https://finanz.orderline.ch/de/ (contao 4.4)
https://contao4.derhaeuptling.com/ (contao 4.7)

**Comment by Toflar** [comment]
Should be fixed in db26a14a925f15ac41c9e081580c52c1a238efa5.
Can you test that before I release 1.1.1, please? :)
