### ISSUE TITLE
Insert-Tag-Service und Contao 4.9

### ISSUE THREAD

**Issue by kp-mtrame** [terminal42/contao-ajaxform#23]
Die Methode sendResponse() von AjaxForm verwendet den neuen Insert-Tag-Service aus Contao 4.13, so dass die Erweiterung nicht mehr mit Contao 4.9 kompatibel ist.

**Comment by aschempp** [comment]
this has meanwhile been fixed in 17cd66cb2acef3b7ff3e8adf0dcc9b367bdc4abc
