### ISSUE TITLE
Support for Contao 4.x

### ISSUE THREAD

**Issue by jankout** [terminal42/contao-ajaxform#9]
Hello, could add the support for Contao 4.x, please? Thank you. Now I cannot install it via composer when I have Contao 4.3.x

**Comment by aschempp** [comment]
I suggest to use the develop branch for now in Contao 4

**Comment by jankout** [comment]
Ok, I'm sorry I don't know how to use the develop branch via composer. Could you send me the command, please? Thank you.

**Comment by aschempp** [comment]
https://getcomposer.org/doc/articles/versions.md#branches

**Comment by fritzmg** [comment]
This can probably be closed now?
